# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Emil Jebastin – Technical Writer
email: emiljebastin07@gmail.com
description: >- 
  A technical writing portfolio that shows my skills in creating clear and structured content using DITA, S1000D, Markdown, and API documentation. It includes real project samples and highlights my ability to write user-friendly and accurate documentation. I’m moving from Aviation to Software and Semiconductor industries.
twitter_username: emiljebastin
github_username: emiljebastin
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Emil Jebastin"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Technical Writer | S1000D | DITA | Markdown | Agile"
  links:
    - label: "LinkedIn"
      icon: "fas fa-fw fa-linkedin"
      url: "www.linkedin.com/in/emil-tech-writer"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/emiljebastin"
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:emiljebastin07@gmail.com"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

  # Navigation Links
main:
  - title: "Home"
    url: /
  - title: "About"
    url: /about/
  - title: "Portfolio"
    url: /portfolio/
  - title: "Projects"
    url: /projects/
  - title: "Resume"
    url: /resume/
  - title: "Contact"
    url: /contact/

# Custom collections
collections:
  portfolio:
    output: true
    permalink: /:collection/:path/

defaults:
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: true
      share: true

